### ISSUE TITLE
v1.0.2 not published?

### ISSUE THREAD

**Issue by Techn1x** [chancancode/ember-concurrency-async#20]
Looks like it's in the package.json and commits but can't seem to install it

![Screenshot from 2022-02-03 14-10-10](https://user-images.githubusercontent.com/1049837/152279829-fa78c066-e60b-47bc-8ef0-b42aea21ef8a.png)

**Comment by chancancode** [comment]
Thanks for bringing it up. I remember I had some trouble getting a package to publish recently but I forgot which one. I’ll look into it again tomorrow, if you don’t hear back soon feel free to ping again. In the meantime see if 1.0 works for you?

**Comment by Techn1x** [comment]
1.0 works great :) just thought it was a little confusing and maybe it was intended to be released. Thanks for the response!
