### ISSUE TITLE
TS error when attempting to invoke .perform() method

### ISSUE THREAD

**Issue by napafundi** [chancancode/ember-concurrency-async#3]
When using the addon and attemping to invoke `.perform()` TS throws the error: `Property 'perform' does not exist on type '() => Promise<...>`.

The concurrency task is setup as follows:

`@restartableTask async foo() {...}`

and then invoked with:

`this.foo.perform()`

**Comment by chancancode** [comment]
This is the same error you would get when using generator functions. TypeScript does know/allow the decorator to change the type of the field. You would have to do a cast (`(this.foo as ...).perform()`) or better, encapsulate it in a utility function. I'll suggest reading the documentation being added in https://github.com/machty/ember-concurrency/pull/357 and see if that helps (and comment there if it didn't).
