### ISSUE TITLE
Possible incompatibility with ember-css-modules

### ISSUE THREAD

**Issue by richard-viney** [chancancode/ember-concurrency-async#4]
I'm seeing asserts start firing from inside `ember-css-modules` after installing this addon, with no code changes made. The app is currently using `ember-concurrency@1.2.0` and `ember-concurrency-decorators@2.0.0` without issue.

The error is `No source specified to local-class lookup`, and is coming from here: https://github.com/salsify/ember-css-modules/blob/master/packages/ember-css-modules/addon/helpers/local-class.js#L6. This is happening because the `from` property isn't set. This property is meant to be set via the template transform here: https://github.com/salsify/ember-css-modules/blob/master/packages/ember-css-modules/index.js#L78.

After installing `ember-concurrency-async` it's as if `ember-css-modulues`' template transform just doesn't get run, which then causes the error observed. It's possible that the problem is inside `ember-css-modules`, but it's interesting that this addon somehow affects a template transform from another addon.

Is there enough information here to suggest a probable cause? Or would it be useful if I kept digging further?

**Comment by dfreeman** [comment]
It doesn't seem like this package should be able to interfere with `ember-css-modules` at all 🤔 

I checked in one of our packages that's a heavy user of ECM, and its styles still resolve correctly and its full test suite still passes with `ember-concurrency{,-decorators,-async}` installed and used to define a task.

Is there anything else that changed in your app other than installing `ember-concurrency-async`? I'm honestly at a loss for how the two could interfere with one another.

**Comment by richard-viney** [comment]
Nothing else changes in the affected app other than installing `ember-concurrency-async`. I'm planning to look into this further in the coming week, so will see what comes of that.

**Comment by jamemackson** [comment]
I am also experiencing this issue when I added this package to an existing project that's on Ember 3.19  - will aim test in isolation to see if I can replicate.

**Comment by jamemackson** [comment]
I created a new isolated test app and was able to replicate the issue where we go from having an app with working css modules that breaks as soon as we install ember-concurrency-async

https://github.com/jamemackson/ember-ec-async-css-modules-test/commits/main

"ember-cli-sass": "^10.0.1",
"ember-concurrency": "^1.2.1",
"ember-concurrency-async": "^0.3.0",
"ember-concurrency-decorators": "^2.0.1",
"ember-css-modules": "^1.3.1",
"ember-css-modules-sass": "^1.1.0",

**Comment by elgordino** [comment]
I am also seeing this issue using the new 0.3.1 release of ember-conccurrency-async.

**Comment by dfreeman** [comment]
Thanks for the thorough reproduction, @jamemackson! Working from there I was able to figure out that `ember-css-modules` was implicitly relying on being initialized before `ember-cli-htmlbars` but didn't have that ordering constraint declared.

Most of the time that just worked out anyway, but the `before: 'ember-cli-babel'` constraint in _this_ package could end up exposing the bug over there, depending on what other addons were present in the build.

This should be fixed in `ember-css-modules@1.3.2`—I can confirm that upgrading ECM in your reproduction app does the trick for me locally.

**Comment by richard-viney** [comment]
Great stuff! I can confirm that this issue is resolved with `ember-css-modules@1.3.2` 🎉.
