### ISSUE TITLE
Babel error when tasks contain async functions

### ISSUE THREAD

**Issue by elgordino** [chancancode/ember-concurrency-async#9]
When a task contains an async function the build fails with this babel error

     Property body of FunctionExpression expected node to be of a type ["BlockStatement"] but instead got "Identifier"

For example this will throw the error:

    @task
    taskWithAsyncStuff = taskFor(async () => {
        await Promise.all([].map(async (a) => a));
    });

But with the 'async' removed from the map it will build fine

    @task
    taskWithoutAsyncStuff = taskFor(async () => {
        await Promise.all([].map((a) => a));
    });

Using

    "ember-concurrency": "1.2.1",
    "ember-concurrency-async": "0.3.0",
    "ember-concurrency-decorators": "2.0.1",
    "ember-concurrency-ts": "0.2.0",

**Comment by chancancode** [comment]
ah I guess we need to limit this to one level cc @jamescdavis

**Comment by jamescdavis** [comment]
Oops, yep, it's a little too eager! I'm on a family vacation this week, but should be able to patch this weekend or early next week at the latest.

**Comment by elgordino** [comment]
Thanks both!

**Comment by elgordino** [comment]
Hi @jamescdavis, just wondering if you had a chance to look into this? Thanks.

**Comment by jamescdavis** [comment]
Released fix as [v0.3.1](https://github.com/chancancode/ember-concurrency-async/releases/tag/v0.3.1).
